name: Bump Version

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Bump Version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: "1.0.${{ github.run_number }}"

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/build.gradle.kts
          git commit -m "ci: bump version [skip ci]" || echo "No changes"
          git push